import { Inter } from "next/font/google";
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "PS | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-light">
      <body className={inter.className}>
        <div id="root">
          <main className={`bg-light ${inter.variable} text-dark`}>
            <NavBar />
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
